export const getPopularStoppages = () => {
  return [
    { name: 'Cliffs of Moher' },
    { name: 'Saint Mary’s Cathedral' },
    { name: 'Killarney National Park' },
    { name: 'Blarney Castle' },
    { name: 'Galway City' },
    { name: 'Rock of Cashel' },
    { name: 'Kilkenny Castle' },
    { name: 'Kildare Village' },
    { name: 'Trinity College & Book of Kells' },
    { name: 'Tollymore Forest Park' },
    { name: 'Doolin' },
    { name: 'King John’s Castle' },
    { name: 'Killarney Town' },
    { name: 'Cobh' },
    { name: 'Connemara National Park' },
    { name: 'Cahir Castle' },
    { name: 'Kilkenny City' },
    { name: 'Irish National Stud' },
    { name: 'Guinness Storehouse' },
    { name: 'Bunratty Castle & Folk Park' },
    { name: 'Limerick City' },
    { name: 'Gap of Dunloe' },
    { name: 'Kinsale' },
    { name: 'Kylemore Abbey' },
    { name: 'Swiss Cottage' },
    { name: 'Medieval Mile' },
    { name: 'Curragh Plains' },
    { name: 'Dublin Castle' },
    { name: 'Hillsborough Castle & Gardens' },
    { name: 'The Burren National Park' },
    { name: 'Adare Village' },
    { name: 'Crag Cave' },
    { name: 'English Market' },
    { name: 'Dunguaire Castle' },
    { name: 'Mitchelstown Cave' },
    { name: 'St Canice’s Cathedral & Round Tower' },
    { name: 'Castletown House' },
    { name: 'Temple Bar' },
    { name: 'Giant’s Causeway' },
    { name: 'Poulnabrone Dolmen' },
    { name: 'Torc Waterfall' },
    { name: 'Cork City' },
    { name: 'Clifden' },
    { name: 'Holycross Abbey' },
    { name: 'Ferns Castle' },
    { name: 'Kilmainham Gaol' },
    { name: 'The Dark Hedges' },
    { name: 'Aillwee Cave' },
    { name: 'Slea Head Drive' },
    { name: 'Midleton Distillery Experience' },
    { name: 'Irish National Heritage Park' },
    { name: 'Howth' },
    { name: 'Stormont Estate' },
    { name: 'Altamont Gardens' },
    { name: 'Russborough House' },
    { name: 'Antrim Castle Grounds' },
    { name: 'Glendalough' },
    { name: 'Newgrange' },
    { name: 'Ulster American Folk Park' },
    { name: 'Waterford City' },
    { name: 'Irish Military War Museum' },
    { name: 'Trim Castle' },
    { name: 'Wexford City' },
    { name: 'Monasterboice' },
    { name: 'Drogheda' },
    { name: 'Powerscourt House & Gardens' },
    { name: 'EPIC The Irish Emigration Museum' },
    { name: 'Titanic Belfast' },
    { name: 'Rock of Dunamase' },
    { name: 'Botanic Gardens Belfast' },
    { name: 'Belfast City Hall' },
    { name: 'Crumlin Road Gaol' },
    { name: 'Dunluce Castle' },
    { name: 'Carrick-a-Rede Rope Bridge' },
    { name: 'Florence Court' },
    { name: 'Marble Arch Caves' },
    { name: 'Arigna Mining Experience' },
    { name: 'Knock Shrine' },
    { name: 'Athenry Castle' },
    { name: 'Castlebar' },
    { name: 'Downpatrick' },
    { name: 'Croagh Patrick' },
    { name: 'Keem Bay' },
    { name: 'Westport Town' },
    { name: 'Slieve League Cliffs' },
    { name: 'Malin Head' },
    { name: 'Cong Abbey' },
    { name: 'Derryglad Folk & Heritage Museum' },
    { name: 'Athlone Castle' },
    { name: 'Clonmacnoise' },
    { name: 'Tullamore D.E.W. Distillery' },
    { name: 'Seán’s Bar' },
    { name: 'Birr Castle Gardens' },
    { name: 'Terra Nova Fairy Garden' },
    { name: 'The Donkey Sanctuary of Mallow' },
    { name: 'Muckross House' },
    { name: 'Glencar Waterfall' },
  ];
};