export const getPopularStoppages = () => {
  return [
    // Level 1
    { name: 'Cliffs of Moher', level: 1 },
    { name: 'Killarney National Park', level: 1 },
    { name: 'Newgrange', level: 1 },
    { name: 'Blarney Castle', level: 1 },
    { name: 'Rock of Cashel', level: 1 },
    { name: "Sean's Bar", level: 1 },
    { name: 'Irish National Stud & Garden', level: 1 },
    { name: 'Kylemore Abbey', level: 1 },
    { name: "Giant's Causeway", level: 1 },
    { name: 'Slieve league cliffs', level: 1 },

    // Level 2
    { name: 'Kilkenny castle', level: 2 },
    { name: 'Doolin', level: 2 },
    { name: 'Limerick city', level: 2 },
    { name: 'Adare', level: 2 },
    { name: 'Bunratty castle and folk park', level: 2 },
    { name: 'Gap of dunloe', level: 2 },
    { name: 'Hillsborough castle and gardens', level: 2 },
    { name: 'Clifden', level: 2 },
    { name: 'The dark hedges', level: 2 },
    { name: 'Slea head drive', level: 2 },
    { name: 'Glendalough', level: 2 },
    { name: 'Trim castle', level: 2 },
    { name: 'Powerscourt house and gardens', level: 2 },
    { name: 'Titanic belfast', level: 2 },
    { name: 'Rock of Dunamase', level: 2 },
    { name: 'Dunluce castle', level: 2 },
    { name: 'Knock shrine', level: 2 },
    { name: 'Croagh patrick', level: 2 },
    { name: 'Cong abbey', level: 2 },
    { name: 'Athlone castle', level: 2 },
    { name: 'Donegal castle', level: 2 },
    { name: 'The Burren National park', level: 2 },
    { name: 'Connemara national park', level: 2 },
    { name: 'Carrick a rede rope bridge', level: 2 },
    { name: 'Cahir castle', level: 2 },
    { name: 'Marble arch caves', level: 2 },
    { name: 'Clonmacnoise', level: 2 },
    { name: 'Irish National heritage park', level: 2 },
    { name: 'Kildare Village', level: 2 },
    { name: 'Game of thrones studio tour', level: 2 },
    { name: 'Tollymore Forest Park', level: 2 },
    { name: 'Carlingford', level: 2 },
    { name: 'Monasterboices High Crosses and Monastic Site', level: 2 },
    { name: 'Galway City', level: 2 },

    // Level 3
    { name: 'Saint Mary’s Cathedral', level: 3 },
    { name: 'Trinity College & Book of Kells', level: 3 },
    { name: 'King John’s Castle', level: 3 },
    { name: 'Cobh', level: 3 },
    { name: 'Kilkenny City', level: 3 },
    { name: 'Guinness Storehouse', level: 3 },
    { name: 'Kinsale', level: 3 },
    { name: 'English Market (Cork)', level: 3 },
    { name: 'Dunguaire Castle', level: 3 },
    { name: 'Mitchelstown Cave', level: 3 },
    { name: 'Temple Bar', level: 3 },
    { name: 'Poulnabrone Dolmen', level: 3 },
    { name: 'Torc Waterfall', level: 3 },
    { name: 'Cork City', level: 3 },
    { name: 'Holycross Abbey', level: 3 },
    { name: 'Ferns Castle', level: 3 },
    { name: 'Midleton Distillery Experience', level: 3 },
    { name: 'Stormont Estate', level: 3 },
    { name: 'Altamont Gardens', level: 3 },
    { name: 'Antrim Castle Grounds', level: 3 },
    { name: 'Waterford City', level: 3 },
    { name: 'Irish Military War Museum', level: 3 },
    { name: 'Botanic Gardens Belfast', level: 3 },
    { name: 'Belfast City Hall', level: 3 },
    { name: 'Florence Court', level: 3 },
    { name: 'Arigna Mining Experience', level: 3 },
    { name: 'Athenry Castle', level: 3 },
    { name: 'Castlebar', level: 3 },
    { name: 'Downpatrick', level: 3 },
    { name: 'Keem Beach', level: 3 },
    { name: 'Westport Town', level: 3 },
    { name: 'Malin Head', level: 3 },
    { name: 'Derryglad Folk & Heritage Museum', level: 3 },
    { name: 'Tullamore D.E.W. Distillery', level: 3 },
    { name: 'Birr Castle Gardens', level: 3 },
    { name: 'Muckross House', level: 3 },
    { name: 'Glencar Waterfall', level: 3 },
    { name: 'Ladies View', level: 3 },
    { name: 'Mizen Head', level: 3 },
    { name: 'Muckross Abbey', level: 3 },
    { name: 'Ross Castle', level: 3 },
    { name: 'Charles Fort', level: 3 },
    { name: 'Belfast Peace Wall', level: 3 },
    { name: 'Hook Lighthouse', level: 3 },
    { name: 'Benbulben', level: 3 },
    { name: 'Mussenden Temple', level: 3 },
    { name: 'Ballintoy Harbour', level: 3 },
    { name: 'Cushendun Caves', level: 3 },
    { name: 'Fanad Head Lighthouse', level: 3 },
    { name: 'Wicklow National Park', level: 3 },
    { name: 'Galway Cathedral', level: 3 },
    { name: 'Ulster American Folk Park', level: 3 },

    // Level 4
    { name: 'Killarney Town', level: 4 },
    { name: 'Swiss Cottage', level: 4 },
    { name: 'Medieval Mile', level: 4 },
    { name: 'Crag Cave', level: 4 },
    { name: 'St Canice’s Cathedral & Round Tower', level: 4 },
    { name: 'Castletown House', level: 4 },
    { name: 'Kilmainham Gaol', level: 4 },
    { name: 'Aillwee Cave', level: 4 },
    { name: 'Howth', level: 4 },
    { name: 'Russborough House', level: 4 },
    { name: 'Wexford City', level: 4 },
    { name: 'Crumlin Road Gaol', level: 4 },
    { name: 'Terra Nova Fairy Garden', level: 4 },
    { name: 'The Donkey Sanctuary of Mallow', level: 4 },
    { name: 'St Patrick’s Cathedral', level: 4 },
    { name: 'Christ Church Cathedral', level: 4 },
    { name: 'Phoenix Park', level: 4 },
    { name: 'Hill of Tara', level: 4 },
    { name: 'National Botanic Gardens', level: 4 },
    { name: 'Fota Wildlife Park', level: 4 },
    { name: 'Jerpoint Abbey', level: 4 },
    { name: 'Dublin Castle', level: 4 },
    { name: 'EPIC The Irish Emigration Museum', level: 4 },
    { name: 'Malahide Castle', level: 4 },
  ];
};